-- ============================================================
-- Ce script SQL ne fonctionne plus sur les nouvelles versions
-- de Supabase (colonnes générées, signatures de fonctions variables).
--
-- Utilise plutôt le script Node.js :
--   npm run seed
--
-- Il utilise le client Supabase officiel pour créer les comptes
-- via l'API Auth (fiable quelle que soit la version).
-- ============================================================
