services:
  - type: web
    name: lithiasis-bilan
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx next start -p $PORT
    healthCheckPath: /api/auth/debug
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        fromService:
          type: web
          name: lithiasis-bilan
          property: url
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
